global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'load_balancer'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'backend_servers'
    static_configs:
      - targets: ['localhost:8001', 'localhost:8002', 'localhost:8003']
